[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["python3.11 -m venv /app/.venv", "source /app/.venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "source /app/.venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port $PORT"
